- hosts: '*'
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  connection: labvix
  gather_facts: 'no'
  tasks:
    - name: Download Newrelic-infra agent
      win_get_url:
        dest: 'C:\Users\Administrador\Downloads'
        url: >-
          https://download.newrelic.com/dot_net_agent/latest_release/NewRelicDotNetAgent_x64.msi
    - name: Install agent
      win_command: NewRelicDotNetAgent_x64.msi /i C:\Users\Administrador\Downloads\newrelic-infra.msi /qb NR_LICENSE_KEY=YOUR_LICENSE_KEY INSTALLLEVEL=1
        state: present
